version: "3.8"

services:
  localstack:
    image: localstack/localstack
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=lambda,cloudformation,s3,iam
      - TZ=America/New_York
      - LAMBDA_EXECUTOR=docker
    privileged: true
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
